package ui.matches

import model.MatchData
import model.PlayerData

val sampleMatchData = MatchData(
    serverName = "Valve Counter-Strike 2 helsinki Server (srcds1053-hel1.380.55)",
    map = "de_overpass",
    totalRounds = 29,
    playerData = listOf(
        PlayerData(
            teamName = "TERRORIST",
            roundsWon = 13,
            steamId = 76561198829151260L,
            name = "\uD835\uDC2C\uD835\uDC10\uD835\uDC2E\uD835\uDC1A\uD835\uDC2B\uD835\uDC1E.",
            rank = 15355,
            kills = 22,
            deaths = 21,
            assists = 6,
            headshotKills = 13,
            damage = 2276,
            utilityDamage = 105,
            enemiesFlashed = 0,
            mvps = 4,
            ping = 37,
            aces = 0,
            fourKRounds = 0,
            threeKRounds = 0
        ),
        PlayerData(
            teamName = "CT",
            roundsWon = 16,
            steamId = 76561198233743220L,
            name = "Von Fieldstream",
            rank = 13674,
            kills = 22,
            deaths = 21,
            assists = 3,
            headshotKills = 7,
            damage = 1948,
            utilityDamage = 96,
            enemiesFlashed = 1,
            mvps = 3,
            ping = 9,
            aces = 0,
            fourKRounds = 0,
            threeKRounds = 3
        ),
        PlayerData(
            teamName = "CT",
            roundsWon = 16,
            steamId = 76561199222453236L,
            name = "EXELANTE",
            rank = 15572,
            kills = 28,
            deaths = 19,
            assists = 5,
            headshotKills = 10,
            damage = 2671,
            utilityDamage = 119,
            enemiesFlashed = 7,
            mvps = 3,
            ping = 101,
            aces = 0,
            fourKRounds = 0,
            threeKRounds = 2
        ),
        PlayerData(
            teamName = "TERRORIST",
            roundsWon = 13,
            steamId = 76561197993420647L,
            name = "✪ Keet.",
            rank = 15256,
            kills = 19,
            deaths = 26,
            assists = 6,
            headshotKills = 8,
            damage = 2062,
            utilityDamage = 20,
            enemiesFlashed = 0,
            mvps = 0,
            ping = 28,
            aces = 0,
            fourKRounds = 0,
            threeKRounds = 0
        ),
        PlayerData(
            teamName = "CT",
            roundsWon = 16,
            steamId = 76561198012323250,
            name = "elf-b0y",
            rank = 14465,
            kills = 21,
            deaths = 25,
            assists = 5,
            headshotKills = 9,
            damage = 2424,
            utilityDamage = 222,
            enemiesFlashed = 3,
            mvps = 4,
            ping = 10,
            aces = 0,
            fourKRounds = 0,
            threeKRounds = 1
        ),
        PlayerData(
            teamName = "TERRORIST",
            roundsWon = 13,
            steamId = 76561199051960182,
            name = "хуйсосня",
            rank = 14773,
            kills = 21,
            deaths = 24,
            assists = 7,
            headshotKills = 9,
            damage = 2333,
            utilityDamage = 114,
            enemiesFlashed = 2,
            mvps = 4,
            ping = 33,
            aces = 0,
            fourKRounds = 0,
            threeKRounds = 1
        ),
        PlayerData(
            teamName = "CT",
            roundsWon = 16,
            steamId = 76561198091781852,
            name = "PerkyT",
            rank = 16287,
            kills = 15,
            deaths = 20,
            assists = 9,
            headshotKills = 3,
            damage = 2190,
            utilityDamage = 98,
            enemiesFlashed = 16,
            mvps = 4,
            ping = 9,
            aces = 0,
            fourKRounds = 0,
            threeKRounds = 0
        ),
        PlayerData(
            teamName = "CT",
            roundsWon = 16,
            steamId = 76561198421510944,
            name = "S11Vaa",
            rank = 14833,
            kills = 24,
            deaths = 21,
            assists = 9,
            headshotKills = 7,
            damage = 2716,
            utilityDamage = 15,
            enemiesFlashed = 12,
            mvps = 2,
            ping = 88,
            aces = 0,
            fourKRounds = 1,
            threeKRounds = 0
        ),
        PlayerData(
            teamName = "TERRORIST",
            roundsWon = 13,
            steamId = 76561199098153905,
            name = "fracta7",
            rank = 15192,
            kills = 15,
            deaths = 19,
            assists = 6,
            headshotKills = 8,
            damage = 1896,
            utilityDamage = 78,
            enemiesFlashed = 6,
            mvps = 1,
            ping = 77,
            aces = 0,
            fourKRounds = 0,
            threeKRounds = 0
        ),
        PlayerData(
            teamName = "TERRORIST",
            roundsWon = 13,
            steamId = 76561199069159750,
            name = "♛ KuB ツ",
            rank = 14999,
            kills = 29,
            deaths = 20,
            assists = 12,
            headshotKills = 16,
            damage = 2774,
            utilityDamage = 125,
            enemiesFlashed = 4,
            mvps = 4,
            ping = 44,
            aces = 0,
            fourKRounds = 1,
            threeKRounds = 3
        )
    )
)